# Generated by Django 5.1.1 on 2024-09-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vpa', models.CharField(blank=True, max_length=100, null=True)),
                ('origin_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mcc', models.CharField(blank=True, max_length=4, null=True)),
                ('mode', models.CharField(choices=[('UPI', 'UPI'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS')], max_length=20)),
                ('txns_id', models.BigIntegerField()),
                ('merchant_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('narration', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
