# Generated by Django 5.1.1 on 2024-09-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0003_alter_transaction_options_alter_transaction_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='txns_id',
            new_name='txn_id',
        ),
    ]
