# Generated by Django 5.1.1 on 2024-09-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0006_fraudtransactiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudtransactiondata',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fraudtransactiondata',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fraudtransactiondata',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
