# Generated by Django 5.1.1 on 2024-09-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0008_transactionrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudtransactiondata',
            name='ml_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactionrules',
            name='merchant_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
