# Generated by Django 5.1.1 on 2024-09-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0009_fraudtransactiondata_ml_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudtransactiondata',
            name='ml_score',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
